import './total-js/support-ukraine';
import './total-js/support-ukraine-list';
import './total-js/API';
import './total-js/listBooks';
import './total-js/modal';
import './total-js/shop-list-di';
import './total-js/scroll-up-btn';
import './total-js/category-books';
import './total-js/load-more-books';
